= Introduction
:published_at: 2016-07-22
:hp-tags: nicolaschaillot, rennes-le-chateau, sougraigne, pech, couty, daffos, rennes-les-bains, Marceille, Aude, saunière

Je suis Nicolas Chaillot, informaticien autodidacte travaillant dana la région Nantaise et "passionné" du mystère de Rennes-le-Château depuis des années (j'indique "passionné" entre guillemets car plus lecteur attentif que chercheur). 

Lisant et relisant les différents posts trouvés ici et là sur différents forums au milieu d'une nuée de commentaires plus ou moins intéressants et/ou crédibles, je me décide un jour, en août 2009, à faire une halte dans le petit village perchée de l'Aude pour y sentir l'atmosphère que j'imaginais pleine de mystères. Malheureusement, peu organisé, je ne l'atteins qu'en toute fin d'après-midi alors que l'église et le domaine de l'abbé Saunières viennent de fermer leurs portes. Malgré tout, se fut une expérience inoubliable, contournant à pied l'ensemble du domaine puis remontant par un chemin escarpé derrière le château, je pu contempler la magnifique vue qui nous ai proposée. 

Puis le temps passant, j'oubli peu à peu cet endroit pour mieux le retrouver en août 2014 où je passe une semaine de vacances non loin de là, à Saint-Jean-de-Paracol sur la route entre Couiza et Puivert. J'en profilte alors pour m'imprégner encore un peu plus de l'ambiance du lieu : visite de l'église en journée et visite guidée "nocture" du domaine. Je rescend de mon petit nuage audois en me jurant, cette fois, de m'investir plus à fond dans la quête du trésor de l'abbé.

Encore une fois, le quotidien prenant le dessus, j'oubliais très vite le petit village du sud-ouest...

Mais comme un refrain qui renvient sans cesse, les deux Rennes me reviennent en tête courant juin 2016, date à laquelle je reprend mes recherches sur le web afin de me remettre à niveaux sur les dernières trouvailles des "vrais" chercheurs".

Avant ce nouveau plongeon dans les méandres des forums consacrés à RLC, voici un résumé de mes connaissances sur l'affaire :

* fin 19ème, l'abbé Saunière arrive à RLC et entreprend des travaux dont le montant dépasse largement les ressources financières dont il dispose
* il semblerait que la décoration de l'église ainsi que les différents éléments de son domaine lui aient permis de transmettre les clés de sa/ses découvertes
* plusieurs personnages sont liés de plus ou moins près au mystère : l'abbé Boudet de Rennes-les-Bains, l'abbé Gelis, Noël Corbu, Marie Dénarnaud, etc.
* le tableau de Nicolas Poussin "Les bergers d'Arcadie" 2nd version semble donner également les clés de l'énigme
* j'ai connaissance également : du tombeau des Pontils, des tableaux de l'église de Rennes-les-bains, du statuaire Giscard, du Tenier, des parchemins, de la tombe de la marquise de Blanchefort et de la dalle de Coumesourde. J'ai également lu et relu les différentes interprétations proposées sur ces différents objets.
* Les oeuvres de Pierre Plantard, Gérard de Sède et Philippe de Chérisey
* Da Vinci Code de Dan Brown ...
* Le DVD "Le trésor des templiers" de Henry Lincoln
* et pour finir un souvenir de vidéo découverte par hasard où Franck Daffos explique, depuis Notre-Dame de Marceille, ce qu'il a trouvé en rapport avec l'affaire. Mais peu au courant de l'avancé de ses recherches à l'époque, je n'y vois que peu de lien avec RLC et y accorde, au final, peu d'attention...

C'est avec ce bagage très léger sur l'affaire que je relance donc ma quête en juin 2016. Après plusieurs soirées à (re..re..re..re)regarder des vidéos qui ne m'apprennent plus rien que je ne savais déjà, je tombe (pendant une longue nuit blanche) sur une vidéo "son" de Franck Daffos interviewé dans une émission de radio (http://www.dailymotion.com/video/xet1j2_rennes-le-chateau-le-secret-derobe_webcam : une vingtaine d'épisodes de 19 minutes au départ puis que je retrouve ici sur youtube ... ouf : https://www.youtube.com/watch?v=Curk20KWdMc). Et là c'est le déclic et je me lève persuadé que ce Monsieur là a tout compris !
Et c'est toujours ce que je pense après avoir avalé en 2 jours les 3 volumes (sur 5) de Franck Daffos : "Le secret dérobé", "Le puzzle reconstitué" et "Le trésor qui rend fou" aux editions ARQA.

Je me décide alors à prendre le plume (ou plutôt le clavier) pour créer ce petit blog sans prétention pour exprimer les quelques doutes et interrogations à propos de certaines informations lues dans ces 3 ouvrages.

Vous trouverez donc dans ce blog quelques questions que je me pose au sujet des différentes interprétations, découvertes, conclusions faites par Franck Daffos (et son compère Didier Hericart de Thury à l'époque) en espérant susciter des réactions et obtenir des réponses, dans la mesure du possible, *constructives et pertinentes*.
